modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
	modId="portablecrafter"
	version="${file.jarVersion}"
	displayName="Portable Crafter"
	description='''
	Adds a handheld version of the vanilla crafting table.
	'''
	authors="MarioAndWeegee3"
	logoFile="assets/portablecrafter/logo.png"
	
	[[dependencies.portablecrafter]]
		modId="forge"
		mandatory=true
		versionRange="[31,)"
		ordering="NONE"
		side="BOTH"

	[[dependencies.portablecrafter]]
		modId="minecraft"
		mandatory=true
		versionRange="[1.15.2]"
		ordering="NONE"
		side="BOTH"
	